### ISSUE TITLE
Entrega Trabajo Practico N°1

### ISSUE THREAD

**Issue by santiagocorbalan** [santiagocorbalan/2020_K2031_Grupo_2#2]
Buenos días solicitamos la corrección del Trabajo Practico N°1 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados

Muy muy buen trabajo !
Me gustó que armaron el excel ! Muy bien, así se generan grandes cantidades de datos de prueba. Eso les suma puntos extra :)

El código está limpio. Es concreto. Utilizan lo justo y necesario sin dar vueltas o usar funciones demás. 

Para la próxima, les pido que se acostumbren a comentar el código.

Nota: 10

FELICITACIONES

@santiagocorbalan @moresisro @Melli11 @briiaanmendez @erikarocha08
