### ISSUE TITLE
Entrega Trabajo Practico N°2

### ISSUE THREAD

**Issue by martinrodrigogerez** [santiagocorbalan/2020_K2031_Grupo_2#3]
Buenos tardes solicitamos la corrección del Trabajo Practico N°2 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Muy buen trabajo =)
Nota 8

Tarea para ir pensando para el trabajo integrador,
¿Qué deberíamos tener presente para detectar y clasificar los diferentes tipos de errores? Esto lo podrán hacer en función del estado en el que se quedó el AFP al recorrer la expresión. 

Saludos,

@Melli11 @GirardelliFrancisco @moresisro @briiaanmendez @santiagocorbalan
