### ISSUE TITLE
Entrega TP4

### ISSUE THREAD

**Issue by moresisro** [santiagocorbalan/2020_K2031_Grupo_2#4]
Buenas @santiagoferreiros , queríamos hacer la entrega del TP4. Actualmente no está funcionando del todo, pero queremos entregarlo de todas formas ya que creemos que sería de gran ayuda recibir feedback como para poder arreglar y mejorar ciertas funcionalidades, pero más que nada porque, después de darle varias vueltas a la resolución a la que llegamos, nos vemos un poco trabados con los resultados. 
A partir de lo que te mostramos el otro día después de clase sobre la gramática, estuvimos corrigiendo algunas cosas según lo que nos marcaste, la unificamos, recortamos y ordenamos, sin embargo probamos reiteradas veces y no estamos pudiendo captar por qué no se hacen los printf de las declaraciones múltiples, declaración de funciones o definición de las mismas, ya que devuelve un syntax error. 

Desde ya muchas gracias

**Comment by santiagoferreiros** [comment]
Estimado grupo,

Lo vemos la próxima clase entre todos. Estuve mirando la gramática y parece prolija. Pero mejor utilizar un modo debug para ver que está ocurriendo.

Considero que se han ocupado en el trabajo para dar por aprobada la instancia de entrega a pesar de no cumplir con todos los requisitos establecidos para la mismta.

Saludos,

Santiago
